---
- hosts: vkr-jenkins
  roles:
          - name: krumstein.ansible_role_jenkins
            jenkins_package_state: present
            jenkins_hostname: vkr-jenkins
            jenkins_http_port: 8080
            jenkins_admin_username: admin
            jenkins_admin_password: admin
            jenkins_plugins:
                    - "ant"
                    - "maven-plugin"
                    - "ssh-slaves"
                    - "workflow-aggregator"
                    - "packer"
                    - "github-oauth"
                    - "gravatar"
                    - "ldap"
                    - "ansible"
                    - "chroot"
                    - "python"
                    - "docker-workflow"
                    - "configuration-as-code"
                    - "configuration-as-code-support"

            jenkins_plugins_install_dependencies: true

  pre_tasks:
          - name: Add ansible-pull
            cron:
                    name: Run ansible-pull site.yml
                    minute: "*/5"
                    job: "ansible-pull -d /etc/ansible/jenkins/ -U https://github.com/krumstein/jenkins-tf.git site.yml >> /var/log/ansible-pull.log"


