---
- hosts: vkr-jenkins
  roles:
          - name: geerlingguy.jenkins
            jenkins_package_state: present
            jenkins_hostname: vkr-jenkins
            jenkins_http_port: 8080
            jenkins_admin_username: admin
            jenkins_admin_password: admin
            jenkins_plugins:
                    - "SSH Slaves"
                    - "Pipeline"
                    - "Packer"
                    - "GitHub Authentication"
                    - "Gravatar"
                    - "LDAP"
                    - "Ansible"
                    - "Chroot"
                    - "Python"
                    - "Docker"
                    - "Docker Pipeline"
                    - "Configuration as Code"
                    - "Configuration as Code Support"

            jenkins_plugins_install_dependencies: true

  tasks:
          - name: Add ansible-pull
            cron:
                    name: Run ansible-pull site.yml
                    minute: "*/5"
                    job: "ansible-pull -d /etc/ansible/jenkins/ -U https://github.com/krumstein/jenkins-tf.git site.yml >> /var/log/ansible-pull.log"


